#!/usr/bin/env python3
"""Record the README gameplay video from the Flutter web build.

Same harness as tools/fdroid/capture_screenshots.py (shared tools/cdp.py: a
stdlib CDP client, a throwaway static server, headless Chrome), plus a
screencast and an ffmpeg assembly step. It:

  1. Serves build/web and boots the app in a phone-portrait viewport.
  2. Injects the committed near-finished Klondike save (tools/video/
     demo_save.json, generated by make_demo_save.dart) into localStorage,
     then reloads so the app boots with a resumable game.
  3. Records a screencast while tapping through: Resume -> Solve -> the win
     cascade -> the records screen.
  4. Assembles the frames -- paced by their real CDP timestamps, not a fixed
     frame rate -- into media/gameplay.mp4 and media/gameplay.gif.

Every tap lands on stable UI chrome (a Resume button, the Solve button, a
tap-anywhere win overlay), never on a computed card position, so the script
does not go stale when board geometry changes.

Unlike every other generator under tools/, the output is NOT byte-
reproducible: frame timing varies run to run. It is therefore excluded from
`tools/fdroid/release.sh --verify-only`.

Prerequisites: `google-chrome` and `ffmpeg` on PATH, and a built web app
(`flutter build web --release`; this script builds it if build/web is
missing).

    python3 tools/video/capture_gameplay.py
    python3 tools/video/capture_gameplay.py --probe   # screenshot each beat
    python3 tools/video/capture_gameplay.py --thumbnail 17.5  # poster frame
"""

import argparse
import base64
import os
import shutil
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir))
from cdp import chrome, screenshot, serve, tap  # noqa: E402

import storage  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))
WEB_DIR = os.path.join(REPO, "build", "web")
FIXTURE = os.path.join(HERE, "demo_save.json")

# Phone portrait, matching the FORMATS["portrait"] logical viewport in
# capture_screenshots.py. dpr 2 (not 3): 720x1280 is ample for a video that
# ships downscaled, and 1080x1920 screencast frames cost throughput that
# shows up as dropped frames during the cascade.
LOGICAL = (360, 640)
DPR = 2

BOOT_SETTLE = 6.0        # Flutter first paint after a (re)load.

# The scripted beats. Each is (label, action, hold_seconds); action is a
# (x, y) logical-pixel tap target or None to simply hold on screen.
#
# Coordinates measured in Task 6 from build/video-probe/*.png (720x1280 @
# DPR 2, so pixel / 2 = logical):
#   resume  - centre of the "Continue playing" Klondike row's ListTile,
#             pixel (360, 666) on 0-menu.png -> logical (180, 333). The
#             whole row is one tap target (ListTile.onTap), not just the
#             "Resume" text/icon.
#   solve   - centre of the gold auto_fix_high icon in the top bar, pixel
#             (498, 53) on the resumed board -> logical (249, 27).
#   records - screen centre; the win overlay is a full-screen
#             HitTestBehavior.opaque tap target, so any point works.
#
# The `cascade` hold is longer than the raw 58-move x 120ms step math
# (~7s) would suggest: that estimate holds under --probe, but a *recording*
# run is also encoding a live JPEG screencast, and the CPU contention that
# creates measurably slows the page's own timers, pushing the observed
# win time past 15s in testing. The overlay also only becomes tappable
# `GameMotion.winCascadeMinimumBeforeDismiss` (3s) after that. 15.0 was
# the smallest value that reliably cleared both in repeated recording
# runs on this machine; below it the `records` tap can fire before the
# win overlay is dismissible and the video ends stuck on the cascade.
#
# The `records` hold (7.0s) is longer than the other static holds because
# it is the video's last beat and its payoff shot: the whole point of the
# preceding cascade is to land here, on a leaderboard that names the game
# just won. 4.0s clocked out at less than a third of the `cascade` hold's
# dwell time and read as a flash-cut in practice -- not enough to read the
# "You won in ... - #N BEST" row, the total-wins tile, and the leaderboard
# rows below it before the recording ends.
BEATS = [
    ("menu",     None,          2.0),
    ("resume",   (180, 333),    3.5),
    ("solve",    (249, 27),     1.5),
    ("cascade",  None,          15.0),
    ("records",  (180, 320),    7.0),
]

TAIL_SECONDS = 6.0
# How long the *rendered* video lingers on its closing frame. This is a
# separate knob from the `records` beat's own hold above, and both matter:
# `build_concat()` only pads a frame's ON-SCREEN duration with the real gap
# to the *next distinct captured frame* -- but Page.screencastFrame only
# fires when something actually repaints, and the records screen stops
# changing about ~2.5s after the tap (once its own fade-in settles), so no
# more frames arrive for the rest of the `records` hold. That makes the
# closing frame of the whole capture the records screen every time, and its
# displayed duration is *this* constant, not whatever's left of the beat's
# hold. Before this fix, TAIL_SECONDS was 2.0s, so the "records" hold's 4.0s
# (and even the 7.0s above) beyond that ~2.5s settle point was silently
# invisible in the rendered video -- extending the hold alone does not make
# the payoff shot dwell any longer on screen. 6.0s was chosen to actually
# deliver on that: comparable to the `records` hold itself, so the
# leaderboard is on screen for several real seconds, not the old ~2.5s.
GIF_FPS = 15
GIF_WIDTH = 270          # px; height follows from the aspect ratio.
THUMBNAIL_WIDTH = 540    # px; height follows from the aspect ratio.

# How long each pump() slice is, before frames are drained/acked again.
# Smaller slices ack sooner after a frame arrives, which matters because
# Chrome withholds the next screencast frame until the previous one is
# acked -- up to a whole slice's worth of dead time otherwise accrues per
# cycle before the next frame is even requested.
PUMP_SLICE = 0.05


def build_concat(frames, tail_seconds):
    """ffmpeg concat-demuxer text for (filename, timestamp) pairs.

    Each frame's duration is the gap to the next one, so playback follows the
    real capture pacing rather than a nominal frame rate. The last file is
    listed twice: the concat demuxer ignores the final entry's duration
    otherwise, and the closing frame would flash past.
    """
    if not frames:
        raise ValueError("no frames captured")
    lines = []
    for i, (name, ts) in enumerate(frames):
        if i + 1 < len(frames):
            # Clamp: CDP timestamps are wall-clock and can arrive out of order.
            duration = max(frames[i + 1][1] - ts, 0.001)
        else:
            duration = tail_seconds
        lines.append(f"file '{name}'")
        lines.append(f"duration {duration:.4f}")
    lines.append(f"file '{frames[-1][0]}'")
    return "\n".join(lines) + "\n"


def _boot(cdp, url):
    log_w, log_h = LOGICAL
    cdp.call("Page.enable")
    cdp.call("Emulation.setDeviceMetricsOverride", width=log_w, height=log_h,
             deviceScaleFactor=DPR, mobile=True)
    cdp.call("Emulation.setTouchEmulationEnabled", enabled=True,
             maxTouchPoints=1)
    cdp.call("Page.navigate", url=url)
    time.sleep(BOOT_SETTLE)
    cdp.call("Runtime.evaluate",
             expression=storage.injection_script(
                 storage.load_fixture(FIXTURE)))
    cdp.call("Page.navigate", url=url)
    time.sleep(BOOT_SETTLE)


def _drain(cdp, frames, frame_dir):
    """Move buffered screencast frames to disk, acking each to Chrome.

    Uses `notify()`, not `call()`, to ack: Chrome will not send the next
    screencast frame until the previous one is acked, so a blocking
    round trip per frame roughly halves the effective capture rate. See
    `CDP.notify()`'s docstring for why discarding the (unread) ack response
    is safe.
    """
    for params in cdp.events("Page.screencastFrame"):
        cdp.notify("Page.screencastFrameAck",
                   sessionId=params["sessionId"])
        name = f"f{len(frames):06d}.jpg"
        with open(os.path.join(frame_dir, name), "wb") as f:
            f.write(base64.b64decode(params["data"]))
        frames.append((name, params["metadata"]["timestamp"]))


def _run_beats(cdp, frames, frame_dir):
    for label, target, hold in BEATS:
        if target is not None:
            tap(cdp, *target)
        # Read frames while the beat plays; without pumping, they pile up
        # unread in the socket and arrive late or not at all.
        end = time.time() + hold
        while time.time() < end:
            cdp.pump(PUMP_SLICE)
            _drain(cdp, frames, frame_dir)
        print(f"[{label}] {len(frames)} frames so far")


def _probe(cdp):
    """Screenshot each beat instead of recording — used to tune coordinates."""
    out_dir = os.path.join(REPO, "build", "video-probe")
    os.makedirs(out_dir, exist_ok=True)
    for i, (label, target, hold) in enumerate(BEATS):
        if target is not None:
            tap(cdp, *target)
        time.sleep(hold)
        screenshot(cdp, os.path.join(out_dir, f"{i}-{label}.png"))
    print(f"\nProbe shots in: {out_dir}")


def _require_ffmpeg():
    """Fail fast, before the ~30 s Chrome capture, if ffmpeg is missing."""
    if shutil.which("ffmpeg") is None:
        sys.exit("error: ffmpeg not found on PATH — needed to assemble the "
                  "captured frames into media/gameplay.mp4 and .gif.")


def _encode(concat_path, frame_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    mp4 = os.path.join(out_dir, "gameplay.mp4")
    # The README embeds the YouTube-hosted mp4 via the poster-frame PNG, not
    # this GIF -- the GIF is for places that can't embed a hosted video link
    # (chat, issue/PR comments, social posts), so it needs to stay small
    # enough to attach/paste there, not fit any README-specific budget.
    gif = os.path.join(out_dir, "gameplay.gif")
    palette = os.path.join(frame_dir, "palette.png")

    subprocess.run(
        ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_path,
         "-vsync", "vfr", "-pix_fmt", "yuv420p", "-c:v", "libx264",
         "-crf", "20", "-movflags", "+faststart",
         # h264 needs even dimensions.
         "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2", mp4],
        cwd=frame_dir, check=True)

    scale = f"fps={GIF_FPS},scale={GIF_WIDTH}:-1:flags=lanczos"
    subprocess.run(
        ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_path,
         "-vf", f"{scale},palettegen=stats_mode=diff", palette],
        cwd=frame_dir, check=True)
    subprocess.run(
        ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_path,
         "-i", palette, "-lavfi",
         f"{scale}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3",
         "-loop", "0", gif],
        cwd=frame_dir, check=True)

    for path in (mp4, gif):
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"{path}  {size_mb:.2f} MB")
        if path == gif and size_mb > 5.0:
            print("  warning: large for a chat/issue attachment — lower "
                  "GIF_FPS or GIF_WIDTH and re-run.")


def _thumbnail(out_dir, timestamp):
    """Extract the committed README poster frame from a recorded MP4.

    GitHub can't embed the YouTube-hosted video inline, so the README links
    a still image instead -- media/gameplay_thumbnail.png. This is that
    image's single source of truth: an ffmpeg single-frame grab at a given
    timestamp, downscaled for a README (the source frame is 720x1280;
    THUMBNAIL_WIDTH keeps the committed PNG well under a README-reasonable
    size). Requires an existing media/gameplay.mp4 -- run a full (non-probe,
    non-thumbnail) recording first, pick a timestamp by eye (e.g. `ffmpeg -i
    media/gameplay.mp4 -vf fps=1/2 /tmp/f_%02d.png` and look through the
    frames), then re-run with that timestamp.
    """
    mp4 = os.path.join(out_dir, "gameplay.mp4")
    if not os.path.isfile(mp4):
        sys.exit(f"error: {mp4} not found -- record a full run first "
                  "(python3 tools/video/capture_gameplay.py).")
    png = os.path.join(out_dir, "gameplay_thumbnail.png")
    subprocess.run(
        ["ffmpeg", "-y", "-ss", str(timestamp), "-i", mp4, "-frames:v", "1",
         "-update", "1",
         "-vf", f"scale={THUMBNAIL_WIDTH}:-1:flags=lanczos", png],
        check=True)
    size_kb = os.path.getsize(png) / 1024
    print(f"{png}  {size_kb:.1f} KB  (t={timestamp}s)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--probe", action="store_true",
                        help="screenshot each beat instead of recording")
    parser.add_argument("--thumbnail", type=float, metavar="SECONDS",
                        help="extract media/gameplay_thumbnail.png from an "
                             "existing media/gameplay.mp4 at SECONDS, "
                             "instead of recording")
    parser.add_argument("--out-dir", default=os.path.join(REPO, "media"))
    args = parser.parse_args()

    if args.thumbnail is not None:
        _require_ffmpeg()
        _thumbnail(args.out_dir, args.thumbnail)
        return

    if not args.probe:
        _require_ffmpeg()  # --probe never encodes, so it never needs ffmpeg.

    if not os.path.isfile(os.path.join(WEB_DIR, "index.html")):
        print("build/web not found — running flutter build web --release ...")
        subprocess.run(["flutter", "build", "web", "--release"],
                       cwd=REPO, check=True)

    log_w, log_h = LOGICAL
    frame_dir = tempfile.mkdtemp(prefix="op-video-")
    try:
        with serve(WEB_DIR) as port, \
                chrome(log_w * DPR, log_h * DPR, device_scale_factor=DPR) as cdp:
            url = f"http://127.0.0.1:{port}/"
            _boot(cdp, url)
            if args.probe:
                _probe(cdp)
                return
            frames = []
            cdp.call("Page.startScreencast", format="jpeg", quality=90,
                     everyNthFrame=1)
            _run_beats(cdp, frames, frame_dir)
            cdp.call("Page.stopScreencast")
            _drain(cdp, frames, frame_dir)

        print(f"captured {len(frames)} frames")
        concat_path = os.path.join(frame_dir, "frames.txt")
        with open(concat_path, "w", encoding="utf-8") as f:
            f.write(build_concat(frames, TAIL_SECONDS))
        _encode(concat_path, frame_dir, args.out_dir)
    finally:
        # A full (non-probe) run writes a few hundred JPEGs plus frames.txt
        # and palette.png into frame_dir. The next task tunes BEATS by
        # running this script repeatedly, so leaving these behind in /tmp
        # on every run — success or failure — would compound fast.
        # ignore_errors=True: a --probe run returns before any frames are
        # written, and a run that fails before mkdtemp's directory is
        # populated should still clean up without raising a second error.
        shutil.rmtree(frame_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
