import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:open_patience/core/game_registry.dart';
import 'package:open_patience/core/game_rules.dart';
import 'package:open_patience/core/pile.dart';
import 'package:open_patience/core/solver.dart';
import 'package:open_patience/persistence/records_repository.dart';
import 'package:open_patience/persistence/shared_prefs_records_repository.dart';
import 'package:open_patience/persistence/stats.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Guards the fixture the gameplay video is recorded from
/// (tools/video/demo_save.json, generated by tools/video/make_demo_save.dart).
///
/// Without these assertions a rules change could quietly make the fixture
/// unsolvable or already-won, and the next `capture_gameplay.py` run would
/// record a video of a stuck board instead of failing loudly.
void main() {
  const String variant = GameRegistry.klondikeDraw1;
  late SharedPrefsRecordsRepository repo;

  setUp(() async {
    final Map<String, dynamic> fixture =
        jsonDecode(File('tools/video/demo_save.json').readAsStringSync())
            as Map<String, dynamic>;
    SharedPreferences.setMockInitialValues(<String, Object>{
      for (final MapEntry<String, dynamic> entry in fixture.entries)
        entry.key: jsonEncode(entry.value),
    });
    repo = SharedPrefsRecordsRepository(await SharedPreferences.getInstance());
  });

  group('demo save fixture', () {
    test('round-trips through the repository', () async {
      final SavedGame? saved = await repo.loadGame(variant);
      expect(saved, isNotNull);
      expect(saved!.variant, variant);
      expect(saved.seed, greaterThan(0));
    });

    test(
      'is a game in progress, not a fresh deal and not already won',
      () async {
        final SavedGame saved = (await repo.loadGame(variant))!;
        final GameRules rules = GameRegistry.rulesFor(variant);
        expect(saved.state.isWon(rules), isFalse);
        expect(saved.state.moveCount, greaterThan(0));
        expect(saved.state.elapsedSeconds, greaterThan(0));
      },
    );

    test('is auto-solvable, so the Solve button is live on resume', () async {
      final SavedGame saved = (await repo.loadGame(variant))!;
      expect(
        solveGreedy(saved.state, GameRegistry.rulesFor(variant)),
        isNotNull,
      );
    });

    test('has at least half the deck on the foundations', () async {
      final SavedGame saved = (await repo.loadGame(variant))!;
      final int onFoundations = saved.state.piles
          .where((Pile p) => p.kind == PileKind.foundation)
          .fold<int>(0, (int sum, Pile p) => sum + p.length);
      expect(onFoundations, greaterThanOrEqualTo(26));
    });

    test('ships prior stats so the records screen is not empty', () async {
      final Stats stats = await repo.statsFor(variant);
      expect(stats.totalWins, greaterThan(0));
      expect(stats.bestWins, isNotEmpty);
      // Stats.recordWin appends one leaderboard row per win (capped at 10),
      // so totalWins and bestWins.length must match. A mismatch (e.g.
      // totalWins: 7 with 3 rows) is a state the app itself can never
      // produce, and it renders as a visibly impossible leaderboard on the
      // records screen the gameplay video ends on.
      expect(stats.totalWins, stats.bestWins.length);
    });
  });
}
